AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample:
  Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a stack
  from this template.'
Parameters:
  KeyEC2Name:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: 'WebServer EC2 instance type'
    Type: String
    Default: t2.small
  SSHLocation:
    Description: 'The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
Mappings:
  AWSInstanceType2Arch:
    t2.small:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t2.small:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    us-east-1:
      PV64: ami-2a69aa47
      HVM64: ami-6869aa05
      HVMG2: ami-61e27177
    us-west-2:
      PV64: ami-7f77b31f
      HVM64: ami-7172b611
      HVMG2: ami-60aa3700
    us-west-1:
      PV64: ami-a2490dc2
      HVM64: ami-31490d51
      HVMG2: ami-4b694d2b
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Enable SSH access via port 22'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups: !Ref InstanceSecurityGroup
      KeyName: !Ref KeyEC2Name
      ImageId: 
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
      UserData:
        'Fn::Base64': 
          !Sub |
            #!/bin/bash
            yum -y update

            # install apache
            yum install httpd24 -y  

            # start server
            service httpd start
            chkconfig httpd on    
Outputs:
  InstanceId:
    Description: 'InstanceId of the newly created EC2 instance'
    Value:
      Ref: MyEC2Instance
  AZ:
    Description: 'Availability Zone of the newly created EC2 instance'
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: 'Public DNSName of the newly created EC2 instance'
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - PublicDnsName
  PublicIP:
    Description: 'Public IP address of the newly created EC2 instance'
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - PublicIp
