AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS creation This example shows an AWS::RDS::DBSecurityGroup resource with ingress authorization from an Amazon EC2 security group referenced by MyEc2SecurityGroup.'

Parameters:
  DBName:
    Type: String
    Default: myDBName
  DBUsername:
    Type: String
    Default: MyDBUsername
  DBPassword:
    Type: String
    Default: MyDBPassword
  DBClass:
    Type: String
    Default: MyDBClass
  MyDBSubnetGroup:
    Type: String
    Default: MyDBSubnetGroup
  DBAllocatedStorage:
    Type: String
    Default: MyDBAllocatedStorage

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: MySQL
      MasterUsername: !Ref DBUsername
      DBInstanceClass: !Ref DBClass
      DBSecurityGroups: !Ref MyDBSubnetGroup
      AllocatedStorage: !Ref DBAllocatedStorage
      MasterUserPassword: !Ref DBPassword

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        EC2SecurityGroupName: !Ref WebServerSecurityGroup
      GroupDescription: Frontend Access

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
